fix(bug): use constant for cache dir
centreon/centreon-awie pull request #50
Opened 2021-05-03 12:31 UTC by jeremyjaouen

this PR intends to fix an issue where an error was thrown while trying to import an archive with AWIE.

2021-05-03 12:55 UTC, sc979 approved these changes

2021-05-03 13:22 UTC, kduret approved these changes

2021-05-03 14:15 UTC, adr-mo approved these changes

2021-05-03 14:35 UTC, lpinsivy requested changes
Don't you forget to add creation of directory if missing as Jira ticket explains?

2021-05-04 06:59 UTC, lpinsivy approved these changes

2021-05-04 07:11 UTC, merged